version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Define environment variables
      - export ANGULAR_VERSION="16.1.4"
      - export NODEJS_VERSION="18.15.0"
      - export AWS_REGION="us-east-1"

      # Install the specified Angular version globally
      - npm install -g @angular/cli@"$ANGULAR_VERSION"

  build:
    commands:
      # Check installed versions and AWS region
      - node -v
      - npm -v
      # - echo "Node.js version: $NODEJS_VERSION"
      # - echo "Angular CLI version: $ANGULAR_VERSION"
      # - echo "AWS Region: $AWS_REGION"
      
      # Install dependencies and build your Angular app
      - npm install 
      - ng build 

artifacts:
  files:
    - dist/**/*
    - appspec.yml
    - after-install.sh
